document.writeln('<div class="footer clearfix">');
document.writeln('<div class="footInfo">');
document.writeln('<div class="wrapper">');
document.writeln('<ul class="fr appDownload">');
document.writeln('<li>');
document.writeln('<img src="../images/public/weixin.jpg" alt="拔萝卜微信">');
document.writeln('<p>微信关注我们</p>');
document.writeln('</li>');
document.writeln('<li>');
document.writeln('<img src="../images/public/appDownload.jpg" alt="拔萝卜客户端">');
document.writeln('<p>拔萝卜客户端下载</p>');
document.writeln('</li>');
document.writeln('<li>');
document.writeln('<a href="https://itunes.apple.com/cn/app/ba-luo-bo-li-cai/id1050564862?l=en&mt=8" target="_blank" title="iPhone"><span class="icon-apple"></span> iPhone</a>');
document.writeln('<a href="http://zhushou.360.cn/detail/index/soft_id/3138682?recrefer=SE_D_拔萝卜" target="_blank" title="Android"><span class="icon-android"></span> Android</a>');
document.writeln('</li>');
document.writeln('</ul>');
document.writeln('<div class="fl">');
document.writeln('<div class="footLogo fl"></div>');
document.writeln('<div class="contactInfo fl">');
document.writeln('<p>客服热线：周一到周五 9:00~18:00</p>');
document.writeln('<p class="phone">400-825-8626</p>');
document.writeln('<p>官方QQ群：498781357</p>');
document.writeln('<p>咨询邮箱：service@baluobo.com</p>');
document.writeln('</div>');
document.writeln('</div>');
document.writeln('</div>');
document.writeln('</div>');
document.writeln('<div class="footNav">');
document.writeln('<div class="wrapper">');
document.writeln('<div class="copyright fr">');
document.writeln('<p>');
document.writeln('拔萝卜版权所有 2016 www.baluobo.com | 备案号：津ICP备15004993号-1 | 站长统计');
document.writeln('</p>');
document.writeln('<p>');
document.writeln('<img src="../images/public/authentication.png" alt="认证">');
document.writeln('</p>');
document.writeln('</div>');
document.writeln('<ul class="fl">');
document.writeln('<li><a href="../about/about.html">关于拔萝卜</a>|</li>');
document.writeln('<li><a href="../about/about.html?index=4">招贤纳士</a>|</li>');
document.writeln('<li><a href="../about/about.html?index=5">联系我们</a>|</li>');
document.writeln('<li><a href="../invest/UserProtocol.html">用户协议</a>|</li>');
document.writeln('<li><a href="../help/financialQA.html">理财问答</a>|</li>');
document.writeln('<li><a href="../help/NoviceGuide.html">新手指引</a></li>');
document.writeln('</ul>');
document.writeln('</div>');
document.writeln('</div>');
document.writeln('</div>');
document.writeln('<ul class="fixedSideBar">');
document.writeln('<li><a href="javascript:void(0);" class="icon-qr-code"><i class="appQrCode"></i></a></li>');
document.writeln('<li><a href="javascript:void(0);" class="icon-weixin"><i class="weixinPopWin"></i></a></li>');
document.writeln('<li><a href="http://wpa.qq.com/msgrd?v=3&uin=1223967410&site=qq&menu=yes" target="_blank" title="客服QQ交谈" rel="nofollow" class="icon-qq"></a></li>');
document.writeln('<li><a href="javascript:void(0);" class="icon-up-arrow backTop" title="回到顶部"></a></li>');
document.writeln('</ul>');